#!/bin/bash

gcc -c ../0x02-functions_nested_loops/0-putchar.c -fpic

gcc -c ../0x02-functions_nested_loops/3-islower.c -fpic

gcc -c ../0x02-functions_nested_loops/4-isalpha.c -fpic

gcc -c ../0x02-functions_nested_loops/6-abs.c -fpic

gcc -c ../0x04-more_functions_nested_loops/0-isupper.c -fpic

gcc -c ../0x04-more_functions_nested_loops/1-isdigit.c -fpic

gcc -c ../0x05-pointers_arrays_strings/2-strlen.c -fpic

gcc -c ../0x05-pointers_arrays_strings/3-puts.c -fpic

gcc -c ../0x05-pointers_arrays_strings/9-strcpy.c -fpic

gcc -c ../0x05-pointers_arrays_strings/100-atoi.c -fpic

gcc -c ../0x06-pointers_arrays_strings/0-strcat.c -fpic

gcc -c ../0x06-pointers_arrays_strings/1-strncat.c -fpic

gcc -c ../0x06-pointers_arrays_strings/2-strncpy.c -fpic

gcc -c ../0x06-pointers_arrays_strings/3-strcmp.c -fpic

gcc -c ../0x07-pointers_arrays_strings/0-memset.c -fpic

gcc -c ../0x07-pointers_arrays_strings/1-memcpy.c -fpic

gcc -c ../0x07-pointers_arrays_strings/2-strchr.c -fpic

gcc -c ../0x07-pointers_arrays_strings/3-strspn.c -fpic

gcc -c ../0x07-pointers_arrays_strings/4-strpbrk.c -fpic

gcc -c ../0x07-pointers_arrays_strings/5-strstr.c -fpic
