#!/bin/bash

gcc -c ./alxschool-low_level_programming/0x04-more_functions_nested_loops/0-isupper.c -o /alxschool-low_level_programming/0x09-static_libraries

gcc -c ./alxschool-low_level_programming/0x07-pointers_arrays_strings/0-memset.c -o /alxschool-low_level_programming/0x09-static_libraries

gcc -c ./alxschool-low_level_programming/0x06-pointers_arrays_strings/0-strcat.c -o /alxschool-low_level_programming/0x09-static_libraries
gcc -c ./alxschool-low_level_programming/0x04-more_functions_nested_loops/1-isdigit.c -o /alxschool-low_level_programming/0x09-static_libraries

